; generated by [Filament Dryer Gcode Script Generator](https://github.com/kforth/Filament-Dryer-GCode-Scripts)
; Copyright 2022  Kestin Goforth
; version: 0.2.2, date: 2022-08-17 14:23:36
; temp: 50 C; time: 240 mins; use_bed: True; use_chamber: True

M117 Heating
M300 S60 P100 ; Chirp
M140 S50; Set target bed temperature
M141 S50; Set target chamber temperature
M190 S50; Wait for target bed temperature
M191 S50; Wait for target chamber temperfature
M300 S60 P100 ; Chirp
M300 S60 P125 ; Chirp

M73 P0 R240
M117 Drying: 240 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P2 R235
M117 Drying: 235 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P4 R230
M117 Drying: 230 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P6 R225
M117 Drying: 225 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P8 R220
M117 Drying: 220 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P10 R215
M117 Drying: 215 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P12 R210
M117 Drying: 210 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P14 R205
M117 Drying: 205 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P16 R200
M117 Drying: 200 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P18 R195
M117 Drying: 195 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P20 R190
M117 Drying: 190 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P22 R185
M117 Drying: 185 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P25 R180
M117 Drying: 180 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P27 R175
M117 Drying: 175 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P29 R170
M117 Drying: 170 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P31 R165
M117 Drying: 165 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P33 R160
M117 Drying: 160 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P35 R155
M117 Drying: 155 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P37 R150
M117 Drying: 150 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P39 R145
M117 Drying: 145 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P41 R140
M117 Drying: 140 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P43 R135
M117 Drying: 135 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P45 R130
M117 Drying: 130 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P47 R125
M117 Drying: 125 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P50 R120
M117 Drying: 120 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P52 R115
M117 Drying: 115 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P54 R110
M117 Drying: 110 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P56 R105
M117 Drying: 105 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P58 R100
M117 Drying: 100 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P60 R95
M117 Drying: 95 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P62 R90
M117 Drying: 90 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P64 R85
M117 Drying: 85 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P66 R80
M117 Drying: 80 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P68 R75
M117 Drying: 75 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P70 R70
M117 Drying: 70 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P72 R65
M117 Drying: 65 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P75 R60
M117 Drying: 60 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P77 R55
M117 Drying: 55 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P79 R50
M117 Drying: 50 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P81 R45
M117 Drying: 45 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P83 R40
M117 Drying: 40 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P85 R35
M117 Drying: 35 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P87 R30
M117 Drying: 30 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P89 R25
M117 Drying: 25 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P91 R20
M117 Drying: 20 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P93 R15
M117 Drying: 15 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P95 R10
M117 Drying: 10 mins Remaining
G4 S60
G4 S60
G4 S60
G4 S60
G4 S60
M73 P97 R5
M117 Drying: 5 mins Remaining
G4 S60
M73 P98 R4
M117 Drying: 4 mins Remaining
G4 S60
M73 P98 R3
M117 Drying: 3 mins Remaining
G4 S60
M73 P99 R2
M117 Drying: 2 mins Remaining
G4 S60
M73 P99 R1
M117 Drying: 1 mins Remaining
G4 S60
M73 P100 R0
M117 Drying Done

M300 S60 P100 ; Chirp
M300 S60 P125 ; Chirp
M300 S60 P150 ; Chirp
M140 S0; Set target bed temperature
M141 S0; Set target chamber temperature

